test_dataset:
  dataset:
    name: PoseDataset
    args:
      anno_file: data/nturgbd/ntu120_3danno.pkl
      pipelines: [
        {name: PreNormalize3D, args: {align_spine: false}},
        {name: GenSkeFeat, args: {dataset: 'nturgb+d', feats:['j']}},
        {name: UniformSampleDecode, args: {clip_len: 90, num_clips: 10}},
        # {name: RandomResizedCrop, args: {p_interval: [0.95, 0.95], clip_len: 120}},
        {name: FormatGCNInput, args: {}},
        {name: Collect, args: {keys: [keypoint, label], meta_keys: []}},
        {name: ToTensor, args: {keys: [keypoint, label]}},
      ]
      split: xset_val
  batch_size: 16
  num_workers: 2

ckp_path: save/experiments/ntu120_xset/ntu120_xset_linear_probe_teacher_600EP/epoch-last.pth