test_dataset:
  dataset:
    name: PoseDataset
    args:
      anno_file: data/nturgbd/ntu120_3danno.pkl
      pipelines: [
        {name: PreNormalize3D, args: {align_spine: false}},
        {name: GenSkeFeat, args: {dataset: 'nturgb+d', feats:['j']}},
        {name: UniformSampleDecode, args: {clip_len: 90, num_clips: 10}},
        # {name: RandomResizedCrop, args: {p_interval: [0.95, 0.95], clip_len: 120}},
        {name: FormatGCNInput, args: {}},
        {name: Collect, args: {keys: [keypoint, label], meta_keys: []}},
        {name: ToTensor, args: {keys: [keypoint, label]}},
      ]
      split: xset_val
  batch_size: 16
  num_workers: 4

# ckp_path: save/ntu60_xsub_fine_tune_800EP_1e-5minLR_3e-4baseLR_0.1LS_0.8LD_0.3dr_0.3DP_new/epoch-last.pth
# ckp_path: save/ntu60_xsub_linear_probe/epoch-best.pth
ckp_path: save/ntu120_xset_fine_tune_3e-4lr_0.80ld_reinit0_swa/epoch-last.pth
ckp_path_: save/ntu120_xset_fine_tune_3e-4lr_0.80ld_reinit0_noEMA/epoch-last.pth