test_dataset:
  dataset:
    name: PoseDataset
    args:
      anno_file: data/nturgbd/ntu120_3danno.pkl
      pipelines: [
        {name: PreNormalize3D, args: {align_spine: false}},
        {name: GenSkeFeat, args: {dataset: 'nturgb+d', feats:['j']}},
        {name: UniformSampleDecode, args: {clip_len: 90, num_clips: 10}},
        {name: FormatGCNInput, args: {}},
        {name: Collect, args: {keys: [keypoint, label], meta_keys: []}},
        {name: ToTensor, args: {keys: [keypoint, label]}},
      ]
      split: xsub_val
  batch_size: 16
  num_workers: 2

ckp_path: save/experiments/ntu120_xsub/ntu120_xsub_linear_probe/epoch-best.pth