train_dataset:
  dataset:
    name: PoseDataset
    args:
      anno_file: data/nturgbd/ntu60_3danno.pkl
      pipelines: [
        {name: PreNormalize3D, args: {align_spine: true}},
        {name: RandomRot, args: {theta: 0.3}},
        {name: GenSkeFeat, args: {dataset: 'nturgb+d', feats:['j']}},
        {name: UniformSampleDecode, args: {clip_len: 90}},
        # {name: RandomResizedCrop, args: {p_interval: [0.5, 1.0], clip_len: 120}},
        {name: FormatGCNInput, args: {}},
        {name: Collect, args: {keys: [keypoint, label], meta_keys: []}},
        {name: ToTensor, args: {keys: [keypoint, label]}},
      ]
      split: xview_train
      # first_k: 100
  batch_size: 24
  num_workers: 8

val_dataset:
  dataset:
    name: PoseDataset
    args:
      anno_file: data/nturgbd/ntu60_3danno.pkl
      pipelines: [
        {name: PreNormalize3D, args: {align_spine: true}},
        {name: GenSkeFeat, args: {dataset: 'nturgb+d', feats:['j']}},
        {name: UniformSampleDecode, args: {clip_len: 90}},
        # {name: RandomResizedCrop, args: {p_interval: [0.95, 0.95], clip_len: 120}},
        {name: FormatGCNInput, args: {}},
        {name: Collect, args: {keys: [keypoint, label], meta_keys: []}},
        {name: ToTensor, args: {keys: [keypoint, label]}},
      ]
      split: xview_val
  batch_size: 32
  num_workers: 8

model:
  name: SkTForClassification
  args:
    encoder_spec:
      name: SkT
      args:
        in_channels: 3
        temporal_segment_size: 3
        spatio_size: 25
        temporal_size: 90
        emb_size: 256
        depth: 8
        num_heads: 8
        att_drop_p: 0.
        forward_drop_p: 0.
        drop_path_p: 0.
    cls_head_spec:
      name: ClassificationHeadLarge
      args:
        n_classes: 60
        hidden_dim: 2048
        num_persons: 2
        num_joints: 25
        drop_p: 0.3
    # encoder_pretrain_weight: /home/rz/nturgbd60_pretrain_skt2vec2_tube_800EP_256BS_WDGroups/epoch-last.pth
    # encoder_pretrain_weight: save/nturgbd60_pretrain_skt2vec2_64BSZ_3D_1e-3baseLR_1e-5minLR_tube5_tau0.2_ema9999_800EP/epoch-600.pth
    encoder_pretrain_weight: /home/rz/epoch-800.pth
    # encoder_pretrain_weight: save/nturgbd60_pretrain_skt2vec2_mask0.90_largeEMA_randomtube6/epoch-300.pth
    # encoder_pretrain_weight: save/nturgbd60_pretrain_skt2vec2_mask0.90_largeEMA_tube5/epoch-300.pth
    encoder_freeze: false
    drop_path_p: 0.30

optimizer:
  name: adamw
  args:
    lr: 1.e-4
    # momentum: 0.9
    weight_decay: 5.e-2
epoch_max: 100

lr_scheduler:
  name: CosineDecayWithWarmup
  args:
    warmup_epochs: 5
    max_epochs: 100
    base_lr: 3.e-4
    min_lr: 1.e-5
    mode: step

label_smoothing: 0.1
layer_decay: 0.8
epoch_val: 1
epoch_save: 200
mode: fine_tune
