train_dataset:
  dataset:
    name: PoseDataset
    args:
      anno_file: data/nturgbd/ntu60_3danno.pkl
      pipelines: [
        {name: PreNormalize3D, args: {}},
        {name: RandomRot, args: {theta: 0.2}},
        {name: GenSkeFeat, args: {dataset: 'nturgb+d', feats:['j']}},
        {name: UniformSampleDecode, args: {clip_len: 120}},
        {name: FormatGCNInput, args: {}},
        {name: Collect, args: {keys: [keypoint, label], meta_keys: []}},
        {name: ToTensor, args: {keys: [keypoint, label]}},
      ]
      split: xsub_train
      # first_k: 100
  batch_size: 32
  num_workers: 8

val_dataset:
  dataset:
    name: PoseDataset
    args:
      anno_file: data/nturgbd/ntu60_3danno.pkl
      pipelines: [
        {name: PreNormalize3D, args: {}},
        {name: GenSkeFeat, args: {dataset: 'nturgb+d', feats:['j']}},
        {name: UniformSampleDecode, args: {clip_len: 120}},
        {name: FormatGCNInput, args: {}},
        {name: Collect, args: {keys: [keypoint, label], meta_keys: []}},
        {name: ToTensor, args: {keys: [keypoint, label]}},
      ]
      split: xsub_val
  batch_size: 32
  num_workers: 8

model:
  name: SkT
  args:
    in_channels: 3
    temporal_segment_size: 4
    spatio_size: 25
    temporal_size: 120
    emb_size: 256
    depth: 8
    n_classes: 60
    num_person: 2
    # drop_p: 0.5
    # forward_drop_p: 0.5
  
# resume: save/nturgbd60_wd1e-3/epoch-last.pth

optimizer:
  name: adam
  args:
    lr: 3.e-4
    weight_decay: 1.e-3
epoch_max: 100

lr_scheduler:
  name: CosineDecayWithWarmup
  args:
    warmup_epochs: 5
    max_epochs: 100
    base_lr: 1.e-4
    min_lr: 1.e-6

epoch_val: 1
epoch_save: 200
