train_dataset:
  dataset:
    name: PoseDataset
    args:
      anno_file: data/nturgbd/ntu120_3danno.pkl
      pipelines: [
        {name: PreNormalize3D, args: {}},
        {name: RandomRot, args: {theta: 0.2}},
        {name: GenSkeFeat, args: {dataset: 'nturgb+d', feats:['j']}},
        {name: UniformSampleDecode, args: {clip_len: 120}},
        {name: FormatGCNInput, args: {}},
        {name: Collect, args: {keys: [keypoint, label], meta_keys: []}},
        {name: ToTensor, args: {keys: [keypoint, label]}},
      ]
      split: xsub_train
      # first_k: 100
  batch_size: 32
  num_workers: 8

val_dataset:
  dataset:
    name: PoseDataset
    args:
      anno_file: data/nturgbd/ntu120_3danno.pkl
      pipelines: [
        {name: PreNormalize3D, args: {}},
        {name: GenSkeFeat, args: {dataset: 'nturgb+d', feats:['j']}},
        {name: UniformSampleDecode, args: {clip_len: 120}},
        {name: FormatGCNInput, args: {}},
        {name: Collect, args: {keys: [keypoint, label], meta_keys: []}},
        {name: ToTensor, args: {keys: [keypoint, label]}},
      ]
      split: xsub_val
  batch_size: 32
  num_workers: 8

model:
  name: SkTForClassification
  args:
    encoder_spec:
      name: SkT
      args:
        in_channels: 3
        temporal_segment_size: 4
        spatio_size: 25
        temporal_size: 120
        emb_size: 256
        depth: 8
        num_heads: 8
        att_drop_p: 0.
        forward_drop_p: 0.
        drop_path_p: 0.
    cls_head_spec:
      name: ClassificationHeadLarge
      args:
        n_classes: 120
        hidden_dim: 2048
        num_persons: 2
        num_joints: 25
        drop_p: 0.3
    # cls_head_spec:
    #   name: ClassificationHeadLight
    #   args:
    #     n_classes: 60
    #     num_persons: 2
    #     drop_p: 0.3
    
  
resume: save/ntu120_xsub_init_smooth0.1/epoch-last.pth

optimizer:
  name: adamw
  args:
    lr: 3.e-4
    weight_decay: 5.e-2
epoch_max: 100

lr_scheduler:
  name: CosineDecayWithWarmup
  args:
    warmup_epochs: 5
    max_epochs: 100
    base_lr: 3.e-4
    min_lr: 1.e-5
    mode: step

label_smoothing: 0.1

epoch_val: 1
epoch_save: 200
