train_dataset:
  dataset:
    name: PoseDataset
    args:
      anno_file: data/nturgbd/ntu60_3danno.pkl
      pipelines: [
        {name: PreNormalize3D, args: {align_spine: false}},
        {name: RandomRot, args: {theta: 0.3}},
        {name: GenSkeFeat, args: {dataset: 'nturgb+d', feats:['j']}},
        {name: UniformSampleDecode, args: {clip_len: 90}},
        # {name: RandomResizedCrop, args: {p_interval: [0.5, 1.0], clip_len: 120}},
        {name: FormatGCNInput, args: {}},
        {name: Collect, args: {keys: [keypoint, label], meta_keys: []}},
        {name: ToTensor, args: {keys: [keypoint, label]}},
      ]
      split: xsub_train
      # first_k: 100
  batch_size: 24
  num_workers: 8

val_dataset:
  dataset:
    name: PoseDataset
    args:
      anno_file: data/nturgbd/ntu60_3danno.pkl
      pipelines: [
        {name: PreNormalize3D, args: {align_spine: false}},
        {name: GenSkeFeat, args: {dataset: 'nturgb+d', feats:['j']}},
        {name: UniformSampleDecode, args: {clip_len: 90}},
        # {name: RandomResizedCrop, args: {p_interval: [0.95, 0.95], clip_len: 120}},
        {name: FormatGCNInput, args: {}},
        {name: Collect, args: {keys: [keypoint, label], meta_keys: []}},
        {name: ToTensor, args: {keys: [keypoint, label]}},
      ]
      split: xsub_val
  batch_size: 32
  num_workers: 8

model:
  name: SkTForClassification
  args:
    encoder_spec:
      name: SkT
      args:
        in_channels: 3
        temporal_segment_size: 3
        spatio_size: 25
        temporal_size: 90
        emb_size: 256
        depth: 8
        num_heads: 8
        att_drop_p: 0.
        forward_drop_p: 0.
        drop_path_p: 0.
    # cls_head_spec:
    #   name: ClassificationHeadTest
    #   args:
    #     n_classes: 60
    #     hidden_dim: 2048
    #     num_persons: 2
    #     num_joints: 25
    #     drop_p: 0.3
    cls_head_spec:
      name: ClassificationHeadLarge
      args:
        n_classes: 60
        hidden_dim: 2048
        num_persons: 2
        num_joints: 25
        drop_p: 0.3
    encoder_pretrain_weight: checkpoints/ntu60_xsub/ntu60_xsub_pretrain_1e-3lr_1e-5min_lr/epoch-800.pth
    # encoder_pretrain_weight: checkpoints/ntu60_xsub/epoch-800.pth
    encoder_freeze: false
    drop_path_p: 0.30
    using_ema_model: true
    init_scale: 1.0
    reinit_last_norm: false
    reinit_last_n_layers: 0

optimizer:
  name: adamw
  args:
    lr: 1.e-4
    # momentum: 0.9
    weight_decay: 5.e-2
epoch_max: 100

# swa:
#   swa_start: 100
#   swa_lr: 5.e-6
#   swa_annel_epochs: 10
#   swa_annel_strategy: cos

lr_scheduler:
  name: CosineDecayWithWarmup
  args:
    warmup_epochs: 5
    max_epochs: 100
    base_lr: 3.e-4
    min_lr: 1.e-5
    mode: step

label_smoothing: 0.1
layer_decay: 0.80
epoch_val: 1
epoch_save: 100
mode: fine_tune
